<!DOCTYPE html
	PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US" xml:lang="en-US">
<head>
<title>Search by filename</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
</head>
<body>
<h1>Search by filename</h1><form method="post" action="/cgi-bin/searchbyname?name=netsrv.run" enctype="multipart/form-data">
Filename to search for: <input type="text" name="name" value="netsrv.run" /><p />Use * for wildcards<hr />Files matching netsrv.run<p /><pre>
1981-11-03    <a href='/BB-D867E-BM/08/new-system/netsrv.run.html'>/BB-D867E-BM/08/new-system/netsrv.run</a>
1981-11-03    <a href='/BB-H137C-BM/06/new-system/netsrv.run.html'>/BB-H137C-BM/06/new-system/netsrv.run</a>
1981-11-03    <a href='/BB-H137D-BM/06/new-system/netsrv.run.html'>/BB-H137D-BM/06/new-system/netsrv.run</a>
1981-11-03    <a href='/bb-d868e-bm_tops20_v41_2020_dist_1of2/01/new-system/netsrv.run.html'>/bb-d868e-bm_tops20_v41_2020_dist_1of2/01/new-system/netsrv.run</a>
1987-03-12    <a href='/SRI_NIC_PERM_FS_1_19910112/01/system/netsrv.run.html'>/SRI_NIC_PERM_FS_1_19910112/01/system/netsrv.run</a>
