<!DOCTYPE html
	PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US" xml:lang="en-US">
<head>
<title>Search by filename</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
</head>
<body>
<h1>Search by filename</h1><form method="post" action="/cgi-bin/searchbyname?name=network.run" enctype="multipart/form-data">
Filename to search for: <input type="text" name="name" value="network.run" /><p />Use * for wildcards<hr />Files matching network.run<p /><pre>
1980-02-18    <a href='/KS10_APT_INSTALL_TAPE/08/uetp/lib/network.run.html'>/KS10_APT_INSTALL_TAPE/08/uetp/lib/network.run</a>
1980-02-18    <a href='/red405a2/11/uetp/lib/network.run.html'>/red405a2/11/uetp/lib/network.run</a>
