<!DOCTYPE html
	PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US" xml:lang="en-US">
<head>
<title>Search by filename</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
</head>
<body>
<h1>Search by filename</h1><form method="post" action="/cgi-bin/searchbyname?name=twoseg.run" enctype="multipart/form-data">
Filename to search for: <input type="text" name="name" value="twoseg.run" /><p />Use * for wildcards<hr />Files matching twoseg.run<p /><pre>
1979-08-21    <a href='/decuslib10-07/01/43,50433/twoseg.run.html'>/decuslib10-07/01/43,50433/twoseg.run</a>
1979-08-21    <a href='/decuslib10-11/01/43,50530/twoseg.run.html'>/decuslib10-11/01/43,50530/twoseg.run</a>
1979-08-21    <a href='/decuslib10-11/01/43,50531/twoseg.run.html'>/decuslib10-11/01/43,50531/twoseg.run</a>
