<!DOCTYPE html
	PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US" xml:lang="en-US">
<head>
<title>Search by filename</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
</head>
<body>
<h1>Search by filename</h1><form method="post" action="/cgi-bin/searchbyname?name=sail.run" enctype="multipart/form-data">
Filename to search for: <input type="text" name="name" value="sail.run" /><p />Use * for wildcards<hr />Files matching sail.run<p /><pre>
1979-07-05    <a href='/decus_20tap1_198111/01/decus/20-0002/sail.run.html'>/decus_20tap1_198111/01/decus/20-0002/sail.run</a>
1979-07-05    <a href='/decuslib20-01/01/decus/20-0002/sail.run.html'>/decuslib20-01/01/decus/20-0002/sail.run</a>
