<!DOCTYPE html
	PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US" xml:lang="en-US">
<head>
<title>Search by filename</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
</head>
<body>
<h1>Search by filename</h1><form method="post" action="/cgi-bin/searchbyname?name=makpak.run" enctype="multipart/form-data">
Filename to search for: <input type="text" name="name" value="makpak.run" /><p />Use * for wildcards<hr />Files matching makpak.run<p /><pre>
1988-08-16    <a href='/k20v7a/06/utilities/makpak.run.html'>/k20v7a/06/utilities/makpak.run</a>
1988-08-16    <a href='/k20v7d/01/utilities/makpak.run.html'>/k20v7d/01/utilities/makpak.run</a>
