RUN SYSTEM:CONLOG
RUN SYSTEM:INFO
RUN SYSTEM:ORION
RUN SYSTEM:QUASAR
RUN SYSTEM:MOUNTR
RUN SYSTEM:MAPPER
RUN SYSTEM:MICOMS
RUN SYSTEM:TVTLOC
RUN SYSTEM:ACJ
job 1 \login operator xx operator
sysdpy ex
get system:batcon
st,b
get SYSTEM:SNDSRV
st,b
get SYSTEM:AUDCHK
st,b
get SYSTEM:IDLER
st,b
get SYSTEM:MAILST
st,b
get SYS:REMIND
st,b
get SYSTEM:LOADED
st,b
set operator-in-attendance
set login any
^Esend * SRI-NIC in operation!
run system:opr
take system:opr.cmd
\
job 2 \login operator xx operator
append ps:<spool>operator-system-log.002.* ps:<spool>operator-old.log
delete ps:<spool>operator-system-log.002.*
assign plpt1:
assign plpt2:
get system:lptspl
st,b
get system:smpspl
st,b
get system:spdspl
st,b
get system:ppnspl
st,b
get system:hpspl
st,b
get system:imgspl
st,b
\
job 3 \login operator xx operator
define ldomain: ps:<domain.local>
define domain: ldomain:
cd ldomain:
run rsvctl
\
job 4 \login operator xx operator
get system:smtjfn
st,b
run sys:mmailr
\
job 5 \login operator xx operator
system:listen sys:whois.exe /port:43 /primary-io /idle-max:15 /forks:2
\
job 6 \login operator xx operator
get ps:<namser>udpser
st,b
get system:tcprcv
st,b
get system:lpd
st,b
system:listen ps:<namser>tcphst.exe /port:101 /primary-io /idle-max:10 /forks:6
\
job 7 \login operator xx operator
system:listen system:regsrv.exe /port:114 /idle-max:10 /prim
system:listen ps:<audit-trail>sids.exe /port:116 /primary-io /idle-max:30 /forks:6
system:listen system:netweb.exe /port:103 /idle-max:10
get system:timsrv
st,b
run system:netsrv
\
job 8 \login domain xx assoc
define df: src:<domain.version5>
run ps:<domain>dsvctl
\
job 9 \login operator xx operator
cd mailb:
get sys:bmailr
st,b
run nicprog:mlsrv
\
job 10 \login operator xx operator
; MKL's stuff is in this job...
system:listen system:tcpmux.exe /port:1 /idle-max:5 /primary-io
run sys:wwv.exe
define dialout: tty1:
get ps:<pager>pager.exe
st,b
get ps:<mkl>netld.exe
st,b
get ps:<mkl>nldlg5.exe
st,b
\
job 11 \login operator xx operator
system:listen sys:whois.exe /port:43 /primary-io /idle-max:15 /forks:2
\
job 12 \login operator xx operator
system:listen sys:whois.exe /port:43 /primary-io /idle-max:15 /forks:2
\
job 13 \login operator xx operator
cd maill:
run sys:lmailr
\
job 14 \login operator xx operator
cd ps:<mkl.nfs.v1>
get portmapper
st,b
get mountserver
st,b
run nfs
\
