!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING RUNOFF
INFORMATION LOGICAL-NAMES
COPY FROM:RUNOFF.CMD TO:*.*.-1
COPY FROM:RUNOFF.TCO TO:*.*.-1
COPY FROM:RUNOFF.CTL TO:*.*.-1
COPY FROM:RNF11-20.DOC TO:*.*.-1
COPY FROM:RUNOFF.EXE TO:*.*.-1
COPY FROM:RUNOFF.HLP TO:*.*.-1
COPY FROM:RUNOFF.MAC TO:*.*.-1
COPY FROM:RUNINP.HLP TO:*.*.-1
COPY FROM:RNFSCC.MAC TO:*.*.-1
COPY FROM:HELPER.REL TO:*.*.-1
COPY FROM:SCAN11.REL TO:*.*.-1
COPY FROM:WILD11.REL TO:*.*.-1
