!COMMAND FILE FOR OBTAINING ALL FILES RELEVANT TO BUILDING RUNOFF
INFORMATION LOGICAL-NAMES

;Files required to build product
COPY FROM-SOURCE:RUNOFF.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:RUNOFF.CTL TO-SOURCE:*.*.-1
COPY FROM-SOURCE:RNFSCC.MAC TO-SOURCE:*.*.-1
COPY FROM-SOURCE:RUNOFF.MAC TO-SOURCE:*.*.-1

;Documentation for product
COPY FROM-SOURCE:RUNOFF.TCO TO-DOC:*.*.-1
COPY FROM-SOURCE:RUNINP.HLP TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:RUNOFF.HLP TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:RUNOFF.DOC TO-DOC:*.*.-1

;Library files used for symbols
;COPY FROM-SUBSYS:WILD11.REL TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:SCAN11.REL TO-SUBSYS:*.*.-1
;COPY FROM-SUBSYS:HELPER.REL TO-SUBSYS:*.*.-1

;Final product
COPY FROM-SOURCE:RUNOFF.EXE TO-SUBSYS:*.*.-1
