! Command file for moving all files relevant to  DSR

INFORMATION LOGICAL-NAMES

;Documentation for product
COPY FROM-SOURCE:RUNOFF.CMD TO-SOURCE:*.*.-1
COPY FROM-SOURCE:RUNOFF.DOC TO-DOC:*.*.-1
COPY FROM-SOURCE:RUNOFF.BWR TO-DOC:*.*.-1

;Final product
COPY FROM-SOURCE:RUNOFF.EXE TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:RUNOFF.HLP TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:TOC.EXE TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:TOC.HLP TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:TCX.EXE TO-SUBSYS:*.*.-1
COPY FROM-SOURCE:TCX.HLP TO-SUBSYS:*.*.-1

;End of Command File
