;JOB%1(2) TO MAKE RUNOFF.SHR FROM RUNOFF.MAC
;SUBMIT WITH COMMAND  .SUBMIT RUNOFF/RESTART:1
;
;REQUIRED FILES:  (LATEST RELEASED VERSIONS)
;[10,7]	PIP.SHR
;	DIRECT.SHR
;	COMPIL.SHR
;	MACRO.SHR
;	LINK.SHR
;	LNK???.SHR
;	CREF.SHR
;	SCAN.REL
;	HELPER.REL
;	WILD.REL
;	JOBDAT.REL
;	C.UNV
;	JOBDAT.UNV
;	SCNMAC.UNV
;[SELF]	RUNOFF.MAC
;	RUNOFF.RNH
;	RUNINP.RNH
;	RNF??.RND  ;DOC FILE
;	RNFDOC.RNS
;
;OUTPUT:
;	RUNOFF.SHR
;	RUNOFF  CREF LISTING
;	RUNOFF.LOG
;	RUNOFF.HLP
;	RUNINP.HLP
;	RNF??.DOC  ;DOC FILE
;	RNFDOC.STD
;
;
;MAKE A RECORD OF WHAT IS BEING USED
.SET WATCH VERSION
.IF (ERROR)  ;TOUGH LUCK
.ASSIGN DEC SYS
.ASSIGN DEC REL
.ASSIGN DEC UNV
.ASSIGN DSK LPT
.DIRECT/CHECKSUM=RUNOFF.MAC,RNF*.RND,RUNOFF.RNH,RUNINP.RNH,RNFDOC.RNS,RUNOFF.CTL
;
;COMPILE, LOAD, AND SAVE; PRODUCING CREF FILE
.LOAD RUNOFF/CREF
.SSAVE DSK:RUNOFF
.VERSION
.IF (ERROR) .E 137
;
;TRY IT JUST TO MAKE SURE IT WORKS
.R PIP
*DSK:TEST.RNO_TTY:
*.CENTRE
*^^THIS IS A TEST.
=
.RUN DSK:RUNOFF
*TEST
.COPY RUNOFF.TMP=RNF???.RND
.R RUNOFF
*RUNOFF.DOC=RUNOFF.TMP
.COPY RUNOFF.TP1=RUNOFF.RNH
.R RUNOFF
*RUNOFF.HLP=RUNOFF.TP1
.COPY RUNINP.TMP=RUNINP.HLP
.R RUNOFF
*RUNINP.HLP=RUNINP.TMP
.COPY RNFDOC.TMP=RNFDOC.RNS
.R RUNOFF
*RNFDOC.STD=RNFDOC.RNS
.DIRECT/CHECKSUM=RUNOFF.SHR
;
;PRODUCE SOURCE LISTING AND TELL OPERATOR
.CREF
.PLEASE  RUNOFF SUCCESSFUL
;
%FIN:
;
;THE FOLLOWING IS THE OLD RUNOFF.OPR, WHICH IS STILL TRUE.
;
;TO LOAD AND SAVE RUNOFF, TYPE:

;	.LOAD RUNOFF
;	.SSAVE RUNOFF
;
.DELETE *.TMP,*.TP1
.KJOB/F
